version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biere_java
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
  adminer:
    image: adminer
    restart: always
    ports:
      - '8989:8080'
